name: scan

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '18 10 * * 3'

permissions:
  contents: read

jobs:
  scan-fossa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Run FOSSA scan and upload build data
        uses: fossa-contrib/fossa-action@v2.0.0
        with:
          # FOSSA Push-Only API Token
          fossa-api-key: 0580abfd8ed19432331e14f6e9eaa7ff
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  scan-codeql:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.3
      - name: Setup Go
        uses: actions/setup-go@v4.0.1
        with:
          go-version: 1.20.x
          cache-dependency-path: |
            **/go.sum
            **/go.mod
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2.20.0
        with:
          languages: go
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2.20.0
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2.20.0
